name: lightning_environment
channels:
  - conda-forge
dependencies:
  - python==3.9
  - mamba
  - pip
  - pip:
    - -r requirements.txt
    - -e .
    - git+https://github.com/rasmuspjohansson/albumentations-multi-channels
