---
model: lenet5
dataset: mnist
path_dataset: False
optimizer: adam
wd: 0.0
ignore_index: -100
label_smoothing: 0.0001
epochs: 10
lr: 0.1
learning_rate_schedule:
 name: CosineAnnealingLR
batchsize: 256
accumulate_grad_batches: 4
gradient_clip_val: 1.0
save_interval: 100
save_dir: "mnistlogs/lenet_origin/"
resume_training: False
val_check_interval: 1
log_every_n_steps: 550
accelerator: auto
state_dict_path_load: False
experment_name: "mnist lenet origin"
loss: cross_entropy
nr_of_visualizations: 0
hours_between_model_save: 0.01
num_sanity_val_steps: 0
